#!/usr/bin/python

import plyproto.model as m
import pdb
import argparse
import plyproto.parser as plyproto
import traceback
import sys
import jinja2
import os
from xos2jinja import XOS2Jinja
import lib

parse = argparse.ArgumentParser(description='XOS code generator')
parse.add_argument('--xosproto', dest='input', action='store',default=None, help='Filename in XOS-enhanced Protobufs')
parse.add_argument('--input', dest='input', action='store',default=None, help='Filename in Protobufs')
parse.add_argument('--output', dest='output', action='store',default=None, help='Output format, corresponding to <output>.yaml file')

args = parse.parse_args()


def include_file(name):
    print name
    return jinja2.Markup(loader.get_source(env, name)[0])

loader = jinja2.PackageLoader(__name__, 'templates')
env = jinja2.Environment(loader=loader)

def main():
    try:
        v = XOS2Jinja()
        parser = plyproto.ProtobufAnalyzer()
        input = open(args.input).read()

        ast = parser.parse_string(input,debug=0)
        ast.accept(v)
        
        template_name = os.path.abspath(args.output)

	os_template_loader = jinja2.FileSystemLoader( searchpath=[os.path.split(template_name)[0]])
        os_template_env = jinja2.Environment(loader=os_template_loader)
        os_template_env.globals['include_file'] = include_file

        for f in dir(lib):
            if f.startswith('xproto'):
                os_template_env.globals[f] = getattr(lib, f)

        template = os_template_env.get_template(os.path.split(template_name)[1])
        rendered = template.render({"proto": {'messages':v.messages}})

        lines = rendered.splitlines()
        current_buffer = []
        for l in lines:
            if (l.startswith('+++')):
                filename = l[4:]
                fil = open(filename,'w')
                buf = '\n'.join(current_buffer)

                obuf = buf
                for d in options.dict:
                    df = open(d).read()
                    d = json.loads(df)

                    pattern = re.compile(r'\b(' + '|'.join(d.keys()) + r')\b')
                    obuf = pattern.sub(lambda x: d[x.group()], buf)
                fil.write(obuf)
                fil.close()

                print 'Written to file %s'%filename
                current_buffer = []
            else:
                current_buffer.append(l)

        if (current_buffer):
            print '\n'.join(current_buffer)


    except Exception as e:
        print "    Error occurred! file[%s]" % (args.input), e
        print '-'*60
        traceback.print_exc(file=sys.stdout)
        print '-'*60
        exit(1)

if __name__=='__main__':
    main()
