#!/bin/sh
yum -y install postgresql postgresql-server
yum -y install python-psycopg2
yum -y install graphviz
yum -y install graphviz-devel
yum -y install graphviz-python
yum -y install libxslt-devel
yum -y install python-pip
yum -y install wget
yum -y install tar
yum -y install gcc
yum -y install libxml2-dev
yum -y install libxslt1-dev
yum -y install python-devel


pip-python install django==1.5
pip-python install djangorestframework
pip-python install markdown  # Markdown support for the browseable API.
pip-python install pyyaml    # YAML content-type support.
pip-python install django-filter  # Filtering support
pip-python install lxml  # XML manipulation library
pip-python install netaddr # IP Addr library
pip-python install pytz
pip-python install django-timezones
pip-python install requests
pip-python install django-crispy-forms
pip-python install django-geoposition
pip-python install django-extensions
pip-python install django-suit
pip-python install django-evolution
pip-python install docutils
pip-python install cython
pip-python install bitfield
pip-python install pygments

easy_install django_evolution

wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-x86_64.tar.bz2

mv ./phantomjs-1.7.0-linux-x86_64.tar.bz2 /usr/local/share

cd /usr/local/share

tar xvf phantomjs-1.7.0-linux-x86_64.tar.bz2

ln -s /usr/local/share/phantomjs-1.7.0-linux-x86_64 /usr/local/share/phantomjs

ln -s /usr/local/share/phantomjs/bin/phantomjs /usr/local/bin/phantomjs

phantomjs --version

