#!/bin/sh
yum -y install bzip2
yum -y install epel-release
yum -y install postgresql postgresql-server
yum -y install python-psycopg2
yum -y install graphviz
yum -y install graphviz-devel
yum -y install graphviz-python
yum -y install libxslt-devel
yum -y install python-pip
yum -y install wget
yum -y install tar
yum -y install gcc
yum -y install libxml2-devel
yum -y install libxslt-devel
yum -y install python-devel


pip install django==1.5
pip install djangorestframework
pip install markdown  # Markdown support for the browseable API.
pip install pyyaml    # YAML content-type support.
pip install django-filter  # Filtering support
pip install lxml  # XML manipulation library
pip install netaddr # IP Addr library
pip install pytz
pip install django-timezones
pip install requests
pip install django-crispy-forms
pip install django-geoposition
pip install django-extensions
pip install django-suit
pip install django-evolution
pip install docutils
pip install cython
pip install bitfield
pip install pygments

easy_install django_evolution

wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-x86_64.tar.bz2

mv ./phantomjs-1.7.0-linux-x86_64.tar.bz2 /usr/local/share

cd /usr/local/share

tar xvf phantomjs-1.7.0-linux-x86_64.tar.bz2

ln -s /usr/local/share/phantomjs-1.7.0-linux-x86_64 /usr/local/share/phantomjs

ln -s /usr/local/share/phantomjs/bin/phantomjs /usr/local/bin/phantomjs

phantomjs --version
