FROM xosproject/xos-base:candidate

ARG XOS_GIT_COMMIT_HASH=unknown
ARG XOS_GIT_COMMIT_DATE=unknown

LABEL XOS_GIT_COMMIT_HASH=$XOS_GIT_COMMIT_HASH
LABEL XOS_GIT_COMMIT_DATE=$XOS_GIT_COMMIT_DATE

# Install XOS client
ADD xos/xos_client /tmp/xos_client

# Install chameleon
ADD containers/xos/tmp.chameleon /tmp/xos_client/xosapi/chameleon

#ENV HOME /root
#WORKDIR /opt/xos

# install the client library and xossh
RUN chdir /tmp/xos_client && make

ENTRYPOINT ["xossh"]
