FROM xosproject/xos-base:candidate

ARG XOS_GIT_COMMIT_HASH=unknown
ARG XOS_GIT_COMMIT_DATE=unknown

LABEL XOS_GIT_COMMIT_HASH=$XOS_GIT_COMMIT_HASH
LABEL XOS_GIT_COMMIT_DATE=$XOS_GIT_COMMIT_DATE

# Install XOS
ADD xos /opt/xos

RUN chmod +x /opt/xos/tools/xos-manage \
 && mkdir -p /opt/cord_profile /opt/xos_services /opt/xos_libraries \
 && sync \
 && /opt/xos/tools/xos-manage genkeys

# Set environment variables
ENV HOME /root

# Define working directory
WORKDIR /opt/xos
