FROM xosproject/xos-client

ADD xos/synchronizers/new_base /opt/xos/synchronizers/new_base
ADD xos/xos/config.py /opt/xos/xos/config.py
ADD xos/xos/logger.py /opt/xos/xos/logger.py
ADD xos/xos/xml_util.py /opt/xos/xos/xml_util.py
ADD xos/xos/__init__.py /opt/xos/xos/__init__.py
ADD xos/synchronizers/__init__.py /opt/xos/synchronizers/__init__.py

ENTRYPOINT ["bash"]
