# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-08 18:28
from __future__ import unicode_literals

import core.models.xosbase_header
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190307_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_decl',
            name='permitted_slices',
            field=models.ManyToManyField(blank=True, related_name='availableNetworks', to='core.Slice'),
        ),
        migrations.AlterField(
            model_name='nodelabel_decl',
            name='node',
            field=models.ManyToManyField(blank=True, related_name='nodelabels', to='core.Node'),
        ),
        migrations.AlterField(
            model_name='xoscore_decl',
            name='name',
            field=core.models.xosbase_header.StrippedCharField(default=b'XOS', help_text=b'Name of XOS', max_length=200, unique=True),
        ),
    ]
