# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190313_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_decl',
            name='description',
            field=models.TextField(blank=True, help_text=b'Description of Service', null=True),
        ),
        migrations.AlterField(
            model_name='service_decl',
            name='public_key',
            field=models.TextField(blank=True, help_text=b'Public key string', null=True),
        ),
        migrations.AlterField(
            model_name='slice_decl',
            name='description',
            field=models.TextField(blank=True, help_text=b'High level description of the slice and expected activities', null=True),
        ),
        migrations.AlterField(
            model_name='trustdomain_decl',
            name='name',
            field=models.CharField(db_index=True, help_text=b'Name of this trust domain', max_length=256),
        ),
    ]
