# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-13 10:25
from __future__ import unicode_literals

import core.models.xosbase_header
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backupoperation_decl_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_decl',
            name='site',
            field=models.ForeignKey(blank=True, help_text=b'The Site this Service belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='core.Site'),
        ),
    ]

