# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_service_decl_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='xoscore_decl',
            name='maintenance_mode',
            field=models.CharField(choices=[(b'NORMAL', b'NORMAL'), (b'DRAIN', b'DRAIN'), (b'READONLY', b'READONLY'), (b'OFFLINE', b'OFFLINE')], default=b'NORMAL', help_text=b'Displays current maintenance mode of XOS', max_length=256),
        ),
    ]
