all: setup_xos

setup_xos:
	bash /opt/xos/scripts/docker_setup_xos
	python /opt/xos/tosca/run.py padmin@vicci.org /opt/xos/configurations/common/fixtures.yaml
	python /opt/xos/tosca/run.py padmin@vicci.org /opt/xos/configurations/common/base.yaml
	python /opt/xos/tosca/run.py padmin@vicci.org /opt/xos/configurations/common/nodes.yaml
