FROM xosproject/cord-app-build
MAINTAINER Andy Bavier <andy@onlab.us>

WORKDIR /src
RUN     git clone https://gerrit.opencord.org/p/config.git && cd config && \
        mvn clean install

CMD bash -c "source /root/.bashrc; onos-app onos-cord-1 install /src/config/target/cord-config-1.0-SNAPSHOT.oar && onos-app onos-cord-1 activate org.opencord.config"