FROM xosproject/cord-app-build
MAINTAINER Andy Bavier <andy@onlab.us>

WORKDIR /src
RUN     git clone -b cord-1.0 https://gerrit.opencord.org/p/vtn.git && cd vtn && \
        mvn clean install

CMD bash -c "source /root/.bashrc; onos-app onos-cord-1 install /src/vtn/target/vtn-*.oar && onos-app onos-cord-1 activate org.opencord.vtn"
