all: admin-openrc flat_name nodes_yaml public_key install_docker

admin-openrc:
	sudo cat /root/setup/admin-openrc.sh > admin-openrc.sh

flat_name:
	sudo bash -c "source /root/setup/admin-openrc.sh ; neutron net-list" |grep flat|awk '{print $$4}' > flat_net_name

nodes_yaml:
	bash ./make-cloudlab-nodes-yaml.sh

public_key: ~/.ssh/id_rsa.pub
	cp ~/.ssh/id_rsa.pub .

~/.ssh/id_rsa.pub:
	cat /dev/zero | ssh-keygen -q -N ""

install_docker:
	which docker > /dev/null || wget -qO- https://get.docker.com/ | sh
	sudo usermod -aG docker $(shell whoami)
