#!/bin/bash

# This is a stub for launching xossh in the xosproject/xos-client container.
# It's assumed that this script is being invoked on the head node. 

docker pull docker-registry:5000/xosproject/xos-client:candidate
docker run --rm -it -v /opt/cord_profile/im_cert_chain.pem:/usr/local/share/ca-certificates/local_certs.crt docker-registry:5000/xosproject/xos-client:candidate -u xosadmin@opencord.org -p `cat /opt/credentials/xosadmin@opencord.org`