all: setup_xos update_certificates run_develserver

setup_xos:
	bash /opt/xos/scripts/docker_setup_xos
	python /opt/xos/tosca/run.py padmin@vicci.org /opt/xos/configurations/kilo-install/cloudlab.yaml
	python /opt/xos/tosca/run.py padmin@vicci.org /opt/xos/configurations/common/cloudlab-nodes.yaml

update_certificates:
	update-ca-certificates

run_develserver:
	cd /opt/xos; python manage.py runserver 0.0.0.0:8000 --insecure
