
###############################################################################
########################## START FRONTEND TASKS ###############################
###############################################################################

RUN mkdir -p /root/setup

RUN echo "autostart=false" >> /etc/supervisor/conf.d/observer.conf

# TODO
# - Enter /opt/xos/core/xoslib and run npm install

CMD /usr/bin/make -C /opt/xos/configurations/frontend -f Makefile.inside
