Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.46.100"
	config.vm.synced_folder "../../../", "/opt/xos"
  config.vm.provision "shell",
	inline: "cd /opt/xos/xos/configurations/frontend && make && echo Vagrant running"
 end
