#! /bin/bash

function wait_postgres {
    sudo -u postgres psql -c '\q'
    while [[ "$?" != "0" ]]; do
        echo Waiting for postgres to start
        sleep 1
        sudo -u postgres psql -c '\q'
    done
}

cd /tmp
service postgresql start
wait_postgres
service supervisor start

exit 0
